export const ACTIONS = {
    USER_PROFILE: {
        UPDATE_USER: "UPDATE_USER"
    },
    TIMEZONE: {
        SET_TIMEZONE: "SET_TIMEZONE"
    },
    CURRENT_COUNTRY: {
        GET_CURRENT_COUNTRY_SUCCESS: "GET_CURRENT_COUNTRY_SUCCESS",
        GET_CURRENT_COUNTRY_ERROR: "GET_CURRENT_COUNTRY_ERROR",
        GET_COUNTRY_SET_LOADER: "GET_COUNTRY_SET_LOADER"
    },
    MODAL_ERROR: {
        CLOSE_MODAL: "CLOSE_MODAL"
    }
}
